export { ICredentialsInput } from './credentials.input';
export { IRegisterInput } from './register.input';
// export { IFollowUpInput } from './follow-up.input'
export { SignupIn } from './signup.in';
export { FilterEspaceIn } from './filter-espacio.in';
export { FilterHospitalIn } from './filter-hospital.in';
export { FilterUserIn } from './filter-user.in';
export { SolicitarSeguimientoIn} from './solicitar-seguimiento.in';
export { IdIn } from './in.in';
export { ConsultarUnSeguimientoIn } from './consultar-un-seguimiento.in';
export { FiltrarSeguimientoIn } from './filtrar-seguimiento.in';
export { AtenderSolicitudSeguimientoIn } from './atender-solicitud-seguimiento.in';
export { AgendarSolicitudSeguimientoIn } from './agendar-solicitud-seguimiento.in';
export { AsignarRoleIn } from './asignar-role-in';
export { SeguimientoCompletoPacienteIn } from './seguimiento-completo-paciente.in';
export { CrearNotificacionIn } from './crear-notificacion.in';
export { ContadoresEstadisticaIn } from './contadores-estadistica.in';
export { ObtenerNotificacionesEnviadasIn } from './obtener-notificaciones-enviadas.in';
export { ObtenerNotificacionesRecibidasIn } from './obtener-notificaciones-recibidas.in';
export { VOPacienteIn } from './vo-paciente.in';
export { MapasDatosIn } from './mapas-datos.in';
export { EditarSeguimientoIn } from './editar-seguimiento.in';
export { VerEspacioIn } from './ver-espacio.in';
export { RecuperarContraseniaIn } from './recuperar-contrasenia.in';
export { ReseteoContraseniaIn } from './reseteo-contrasenia.in';