module.exports.data2 = [
    {
       "_id":"5f95a931726f29001edad558",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f53feee2c4cc3001ed3f4af",
          "nombre":"América",
          "descripcion":null,
          "idEspacio":"5f53fe752c4cc3001ed3f4a0",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"REVISADO_SIN_LLAMADA",
       "temperatura":45,
       "ritmo_cardiaco":123,
       "saturacion_oxigeno":123,
       "dificultad_respirar":"NO",
       "examen":null,
       "nota_paciente":"primero",
       "observacion_doctor":"actualiza",
       "estado_diario_paciente":"EMPEORANDO",
       "fecha_atencion_medica":"2020-10-25T13:25:58.000Z",
       "diagnostico_actual":null,
       "aislamiento_desde":"2020-10-25T11:34:57.000Z",
       "aislamiento_hasta":"2020-10-28T11:34:57.000Z",
       "latitud":null,
       "longitud":null,
       "createAt":"2020-10-25T11:34:57.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
        "_id":"5f95a931726f29001edadxxx",
        "idPaciente":{
           "name":"Darwin",
           "lastname":"Guailla",
           "__typename":"PacienteSegCompOut"
        },
        "idDoctor":{
           "name":"Darwin",
           "lastname":"Guailla",
           "__typename":"DoctorSegCompOut"
        },
        "idHospital":{
           "_id":"5f53feee2c4cc3001ed3f4af",
           "nombre":"América",
           "descripcion":null,
           "idEspacio":"5f53fe752c4cc3001ed3f4a0",
           "estado_entidad":"ACTIVO",
           "__typename":"HospitalSegCompOut"
        },
        "estado":"REVISADO_SIN_LLAMADA",
        "temperatura":45,
        "ritmo_cardiaco":123,
        "saturacion_oxigeno":123,
        "dificultad_respirar":"NO",
        "examen":null,
        "nota_paciente":"primero",
        "observacion_doctor":"actualiza",
        "estado_diario_paciente":"EMPEORANDO",
        "fecha_atencion_medica":"2020-10-25T13:25:58.000Z",
        "diagnostico_actual":null,
        "aislamiento_desde":"2020-10-25T11:34:57.000Z",
        "aislamiento_hasta":"2020-10-28T11:34:57.000Z",
        "latitud":null,
        "longitud":null,
        "createAt":"2020-10-26T11:34:57.000Z",
        "__typename":"SeguimientoSegCompOut"
     },
    {
       "_id":"5f983e48662f52001e2c7358",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":null,
       "idHospital":{
          "_id":"5f53feee2c4cc3001ed3f4af",
          "nombre":"América",
          "descripcion":null,
          "idEspacio":"5f53fe752c4cc3001ed3f4a0",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"SOLICITADO_SIN_LLAMADA",
       "temperatura":45,
       "ritmo_cardiaco":0,
       "saturacion_oxigeno":0,
       "dificultad_respirar":"SI",
       "examen":null,
       "nota_paciente":"",
       "observacion_doctor":null,
       "estado_diario_paciente":"MEJOR_EVOLUCION",
       "fecha_atencion_medica":null,
       "diagnostico_actual":null,
       "aislamiento_desde":"2020-10-25T11:34:57.000Z",
       "aislamiento_hasta":"2020-10-27T11:34:57.000Z",
       "latitud":null,
       "longitud":null,
       "createAt":"2020-10-27T10:35:36.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5f99877de23728001ecf9383",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":null,
       "idHospital":{
          "_id":"5f53feee2c4cc3001ed3f4af",
          "nombre":"América",
          "descripcion":null,
          "idEspacio":"5f53fe752c4cc3001ed3f4a0",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"SOLICITADO_SIN_LLAMADA",
       "temperatura":35,
       "ritmo_cardiaco":122,
       "saturacion_oxigeno":0,
       "dificultad_respirar":"SI",
       "examen":null,
       "nota_paciente":"dolor de muelas",
       "observacion_doctor":null,
       "estado_diario_paciente":"MEJOR_EVOLUCION",
       "fecha_atencion_medica":null,
       "diagnostico_actual":null,
       "aislamiento_desde":null,
       "aislamiento_hasta":null,
       "latitud":null,
       "longitud":null,
       "createAt":"2020-10-28T10:00:13.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5f9afc118774ed001e5f798d",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f53feee2c4cc3001ed3f4af",
          "nombre":"América",
          "descripcion":null,
          "idEspacio":"5f53fe752c4cc3001ed3f4a0",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"AGENDADO",
       "temperatura":32,
       "ritmo_cardiaco":122,
       "saturacion_oxigeno":124,
       "dificultad_respirar":"NO",
       "examen":null,
       "nota_paciente":"nota uno",
       "observacion_doctor":null,
       "estado_diario_paciente":"EMPEORANDO",
       "fecha_atencion_medica":null,
       "diagnostico_actual":null,
       "aislamiento_desde":null,
       "aislamiento_hasta":null,
       "latitud":null,
       "longitud":null,
       "createAt":"2020-10-29T12:29:53.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5f9b25dd7e99b3001eb2cd42",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f53feee2c4cc3001ed3f4af",
          "nombre":"América",
          "descripcion":null,
          "idEspacio":"5f53fe752c4cc3001ed3f4a0",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"REVISADO_SIN_LLAMADA",
       "temperatura":39,
       "ritmo_cardiaco":144,
       "saturacion_oxigeno":155,
       "dificultad_respirar":"SI",
       "examen":null,
       "nota_paciente":"tercer seguimiento",
       "observacion_doctor":"Yes where is the truncated text and how do you show your full text. You have to show the full text somewhere. But How? xxx",
       "estado_diario_paciente":"IGUAL_EVOLUCION",
       "fecha_atencion_medica":"2020-10-29T23:46:13.000Z",
       "diagnostico_actual":null,
       "aislamiento_desde":null,
       "aislamiento_hasta":null,
       "latitud":null,
       "longitud":null,
       "createAt":"2020-10-29T15:28:13.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5f9b02a98774ed001e5f798f",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f53feee2c4cc3001ed3f4af",
          "nombre":"América",
          "descripcion":null,
          "idEspacio":"5f53fe752c4cc3001ed3f4a0",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"REVISADO_SIN_LLAMADA",
       "temperatura":32,
       "ritmo_cardiaco":122,
       "saturacion_oxigeno":124,
       "dificultad_respirar":"SI",
       "examen":null,
       "nota_paciente":"nota uno",
       "observacion_doctor":"Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scramble.",
       "estado_diario_paciente":"MEJOR_EVOLUCION",
       "fecha_atencion_medica":"2020-10-29T12:59:06.000Z",
       "diagnostico_actual":null,
       "aislamiento_desde":null,
       "aislamiento_hasta":null,
       "latitud":null,
       "longitud":null,
       "createAt":"2020-10-29T12:58:01.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5f9c0c9ee1b8ba001e2c544a",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f53feee2c4cc3001ed3f4af",
          "nombre":"América",
          "descripcion":null,
          "idEspacio":"5f53fe752c4cc3001ed3f4a0",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"REVISADO_SIN_LLAMADA",
       "temperatura":30,
       "ritmo_cardiaco":122,
       "saturacion_oxigeno":80,
       "dificultad_respirar":"NO",
       "examen":"NO_REQUIERE",
       "nota_paciente":"primer seguimiento del día",
       "observacion_doctor":"primera atención",
       "estado_diario_paciente":"EMPEORANDO",
       "fecha_atencion_medica":"2020-10-30T11:25:02.000Z",
       "diagnostico_actual":"PROBABLE",
       "aislamiento_desde":null,
       "aislamiento_hasta":null,
       "latitud":null,
       "longitud":null,
       "createAt":"2020-10-30T07:52:46.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5f9c527ce1b8ba001e2c5a99",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f53feee2c4cc3001ed3f4af",
          "nombre":"América",
          "descripcion":null,
          "idEspacio":"5f53fe752c4cc3001ed3f4a0",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"REVISADO_SIN_LLAMADA",
       "temperatura":40,
       "ritmo_cardiaco":100,
       "saturacion_oxigeno":90,
       "dificultad_respirar":"NO",
       "examen":null,
       "nota_paciente":"segundo envío de datos ",
       "observacion_doctor":"este paciente no presenta síntomas respiratorios",
       "estado_diario_paciente":"IGUAL_EVOLUCION",
       "fecha_atencion_medica":"2020-10-30T12:52:51.000Z",
       "diagnostico_actual":null,
       "aislamiento_desde":null,
       "aislamiento_hasta":null,
       "latitud":null,
       "longitud":null,
       "createAt":"2020-10-30T12:50:52.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5f9f6fb78561c5001e4f60f6",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":null,
       "idHospital":{
          "_id":"5f4f13707bbde4001ecf24da",
          "nombre":"La Laguna",
          "descripcion":null,
          "idEspacio":"5f4f10c47bbde4001ecf24c9",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"SOLICITADO_SIN_LLAMADA",
       "temperatura":38,
       "ritmo_cardiaco":122,
       "saturacion_oxigeno":120,
       "dificultad_respirar":"NO",
       "examen":null,
       "nota_paciente":"Primera del día",
       "observacion_doctor":null,
       "estado_diario_paciente":"MEJOR_EVOLUCION",
       "fecha_atencion_medica":null,
       "diagnostico_actual":null,
       "aislamiento_desde":"2020-11-01T11:34:57.000Z",
       "aislamiento_hasta":"2020-11-03T11:34:57.000Z",
       "latitud":null,
       "longitud":null,
       "createAt":"2020-11-01T21:32:23.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5f9f93a2a587ee001edd93df",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":null,
       "idHospital":{
          "_id":"5f4f13707bbde4001ecf24da",
          "nombre":"La Laguna",
          "descripcion":null,
          "idEspacio":"5f4f10c47bbde4001ecf24c9",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"SOLICITADO_SIN_LLAMADA",
       "temperatura":38,
       "ritmo_cardiaco":0,
       "saturacion_oxigeno":0,
       "dificultad_respirar":"NO",
       "examen":null,
       "nota_paciente":"primera ",
       "observacion_doctor":null,
       "estado_diario_paciente":"IGUAL_EVOLUCION",
       "fecha_atencion_medica":null,
       "diagnostico_actual":null,
       "aislamiento_desde":"2020-11-01T11:34:57.000Z",
       "aislamiento_hasta":"2020-11-02T11:34:57.000Z",
       "latitud":null,
       "longitud":null,
       "createAt":"2020-11-02T00:05:38.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5fa0f91bfcdca8001e0eb82e",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f4f13707bbde4001ecf24da",
          "nombre":"La Laguna",
          "descripcion":null,
          "idEspacio":"5f4f10c47bbde4001ecf24c9",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"REVISADO_SIN_LLAMADA",
       "temperatura":40,
       "ritmo_cardiaco":0,
       "saturacion_oxigeno":0,
       "dificultad_respirar":"NO",
       "examen":null,
       "nota_paciente":"tercer seguimiento",
       "observacion_doctor":"atendido",
       "estado_diario_paciente":"IGUAL_EVOLUCION",
       "fecha_atencion_medica":"2020-11-03T01:32:02.000Z",
       "diagnostico_actual":"CONFIRMADO",
       "aislamiento_desde":"2020-11-01T11:34:57.000Z",
       "aislamiento_hasta":"2020-11-03T11:34:57.000Z",
       "latitud":null,
       "longitud":null,
       "createAt":"2020-11-03T01:30:51.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5fa0f66afcdca8001e0eb82d",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f4f13707bbde4001ecf24da",
          "nombre":"La Laguna",
          "descripcion":null,
          "idEspacio":"5f4f10c47bbde4001ecf24c9",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"REVISADO_SIN_LLAMADA",
       "temperatura":45,
       "ritmo_cardiaco":123,
       "saturacion_oxigeno":90,
       "dificultad_respirar":"NO",
       "examen":null,
       "nota_paciente":"Dolor de garganta",
       "observacion_doctor":"primera revisión",
       "estado_diario_paciente":"IGUAL_EVOLUCION",
       "fecha_atencion_medica":"2020-11-03T01:19:54.000Z",
       "diagnostico_actual":"CONFIRMADO",
       "aislamiento_desde":"2020-11-01T11:34:57.000Z",
       "aislamiento_hasta":"2020-11-03T11:34:57.000Z",
       "latitud":null,
       "longitud":null,
       "createAt":"2020-11-03T01:19:22.000Z",
       "__typename":"SeguimientoSegCompOut"
    },
    {
       "_id":"5fa0ed22fcdca8001e0eb82c",
       "idPaciente":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"PacienteSegCompOut"
       },
       "idDoctor":{
          "name":"Darwin",
          "lastname":"Guailla",
          "__typename":"DoctorSegCompOut"
       },
       "idHospital":{
          "_id":"5f4f13707bbde4001ecf24da",
          "nombre":"La Laguna",
          "descripcion":null,
          "idEspacio":"5f4f10c47bbde4001ecf24c9",
          "estado_entidad":"ACTIVO",
          "__typename":"HospitalSegCompOut"
       },
       "estado":"REVISADO_SIN_LLAMADA",
       "temperatura":38,
       "ritmo_cardiaco":0,
       "saturacion_oxigeno":0,
       "dificultad_respirar":"SI",
       "examen":null,
       "nota_paciente":"dolor de cabeza",
       "observacion_doctor":"primera atención del día",
       "estado_diario_paciente":"IGUAL_EVOLUCION",
       "fecha_atencion_medica":"2020-11-03T00:47:56.000Z",
       "diagnostico_actual":"PROBABLE",
       "aislamiento_desde":null,
       "aislamiento_hasta":null,
       "latitud":null,
       "longitud":null,
       "createAt":"2020-11-03T00:39:46.000Z",
       "__typename":"SeguimientoSegCompOut"
    }
  ]; 