export enum DiagnosticoActualEnum {
    AISLAMIENTO_PREVENTIVO = "AISLAMIENTO_PREVENTIVO",
    SOSPECHOSO = "SOSPECHOSO",
    CONFIRMADO = "CONFIRMADO",
    RECUPERADO = "RECUPERADO",
    FALLECIDO = "FALLECIDO",
    HOSPITALIZADO = "HOSPITALIZADO",
    
}



