export enum DiagnosticoActualEnum {
    // AISLAMIENTO_PREVENTIVO = "AISLAMIENTO_PREVENTIVO",
    PROBABLE = "PROBABLE",
    SOSPECHOSO = "SOSPECHOSO",
    CONFIRMADO = "CONFIRMADO",
    RECUPERADO = "RECUPERADO",
    FALLECIDO = "FALLECIDO",
    HOSPITALIZADO = "HOSPITALIZADO"    
}