export enum EstadisticaTipoEnum {
    COUNT_PACIENTES_POR_DIA_POR_DIAGNOSTICO="COUNT_PACIENTES_POR_DIA_POR_DIAGNOSTICO",
    COUNT_PACIENTES_POR_DIAGNOSTICO="COUNT_PACIENTES_POR_DIAGNOSTICO",
    COUNT_USER_POR_ROLE_AND_HOSPITAL="COUNT_USER_POR_ROLE_AND_HOSPITAL"
}
