export enum ExamenTipoEnum{
    NO_REQUIERE="NO_REQUIERE",
    SOLICITADA="SOLICITADA",
    P_RAPIDA_IGC_POSITIVA="P_RAPIDA_IGC_POSITIVA",
    P_RAPIDA_IGM_POSITIVA="P_RAPIDA_IGM_POSITIVA",
    P_RAPIDA_IGG_E_IGM_NEGATIVA="P_RAPIDA_IGG_E_IGM_NEGATIVA",
    P_RAPIDA_IGG_E_IGM_POSITIVA="P_RAPIDA_IGG_E_IGM_POSITIVA",
    PCR_TR_POSITIVA="PCR_TR_POSITIVA",
    PCR_TR_NEGATIVA="PCR_TR_NEGATIVA",
    P_RAPIDA_INDETERMINADA="P_RAPIDA_INDETERMINADA",
    PCR_INDETERMINADA="PCR_INDETERMINADA"
}