export  enum SeguimientoEstadoEnum{
    SOLICITADO_CON_LLAMADA=0,
    SOLICITADO_SIN_LLAMADA=1,
    REVISADO_CON_LLAMADA=2,
    REVISADO_SIN_LLAMADA=3,
    INACTIVE_BY_ADMIN=4,
    INACTIVE_BY_USER=5,
    AGENDADO=6
}
