export  enum SeguimientoEstadoEnum{
    SOLICITADO_CON_LLAMADA="SOLICITADO_CON_LLAMADA",
    SOLICITADO_SIN_LLAMADA="SOLICITADO_SIN_LLAMADA",
    REVISADO_CON_LLAMADA="REVISADO_CON_LLAMADA",
    REVISADO_SIN_LLAMADA="REVISADO_SIN_LLAMADA",
    INACTIVE_BY_ADMIN="INACTIVE_BY_ADMIN",
    INACTIVE_BY_USER="INACTIVE_BY_USER",
    AGENDADO="AGENDADO"
}
